Samples/Outlook.RelatedData/OutlookAddInOffice365Api-Debug.xml

It looks like that https://login.microsoftonline.com should be introduced in the appdomains of the office app. Otherwise and X-Frame will prevent the authentication flow to happen in the sandboxed iFrame containing the app.
Resubmission of PR #7

Add login.microsoftonline.com to the app domains

---

Samples/excel-shared-runtime-global-state/README.md
Samples/excel-shared-runtime-scenario/README.md

The shared runtime is GA, so I removed the readme comments about preview requirements. Fixes #101

Removed preview requirement from shared runtime samples

---

Samples/auth/Office-Add-in-Microsoft-Graph-React/README.md
Samples/auth/Office-Add-in-Microsoft-Graph-React/login/login.ts
Samples/auth/Office-Add-in-Microsoft-Graph-React/logout/logout.ts
Samples/auth/Office-Add-in-Microsoft-Graph-React/package-lock.json
Samples/auth/Office-Add-in-Microsoft-Graph-React/package.json

Hello! Jason from the MSAL.js team. This PR upgrades the Office Addin MS Graph React sample to use MSAL Browser, our new library which switches from the Implicit Flow to the Auth Code Flow w/ PKCE for SPAs. One notable advantage of upgrading to MSAL Browser is that is it should mitigate [problems caused by the Edge webview truncating long URLs](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2726). 
I have tested …

Upgrade MSAL.js to v2

---

Samples/office-contextual-tabs/manifest.xml
Samples/office-contextual-tabs/package-lock.json
Samples/office-contextual-tabs/package.json

Manifest Validation Failed due to misplaced Hosts section
Moved Hosts section to under AppDomains
Also upped the office-addin-manifest to the latest package for the latest validator (solving the failing validation on localhost urls)
No additional guidance needed. 
To repro run:
npm run validate 
before and after the change

Fixed invalid Manifest on failing validation

---

Samples/office-contextual-tabs/src/commands/ribbonJSON.js

Fixes a bug in the contextual tabs sample where if the task pane is displayed, and you select the "Show task pane" button on the "Table Data" contextual tab, you end up with the same task pane displayed twice.
With this fix it only ever shows the 1 task pane.
Solution is to not reference an id or URL location in the JSON (which sends an intent to launch a different task pane rather than default.)

Contextual tabs: fix issue with two task panes getting displayed

---

Samples/outlook-set-signature/src/runtime/Js/autorunshared.js
Samples/outlook-set-signature/src/runtime/Js/autorunweb.js

There's a bug where an embedded image won't embed correctly when in Outlook on the web creating an appointment. This fixes that. Also some refactoring and renames to better identify the signature details passed around (which is an object, not a string).

fix bug so image will embed in Outlook on the web appointments

---

Samples/excel-insert-file/index.js

| Related issues? | no  |
Adds a try...catch block. An error can occur when inserting worksheets in Excel on the web. If a worksheet has unsupported features, such as charts, the insertWorksheetsFromBase64 method will fail. Added code comments on how to work with this.

Add try catch for inserting external Excel files

---

Samples/Excel.OfflineStorageAddin/README.md
Samples/VSTO-shared-code-migration/README.md
Samples/auth/Office-Add-in-ASPNET-SSO/README.md
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/README.md
Samples/auth/Office-Add-in-Microsoft-Graph-React/README.md
Samples/auth/Office-Add-in-NodeJS-SSO/README.md
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/README.md
Samples/auth/Outlook-Add-in-SSO/README.md
Samples/excel-insert-file/README.md
Samples/excel-keyboard-shortcuts/README.md
Samples/excel-shared-runtime-global-state/README.md
Samples/excel-shared-runtime-scenario/README.md
Samples/office-contextual-tabs/README.md
Samples/outlook-set-signature/README.md
Samples/outlook-tag-external/README.md

| Related issues? | nonde |
This is an update to the sample code gallery metadata to provide each sample with a unique unchanging name (or URL in the gallery). Will prevent the gallery from using the H1 title of the readmes, which can change and then break a URL link in the code gallery. This ensure URLs are always the same even if you change the H1

add consistent short urls for code gallery

---

Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Web.config

| Bug fix?        |  yes                               |
| Related issues? | fixes #205       |
Still wasn't working properly due to the mismatched version of DotNetCompilerPlatform in web.config.
Ran "Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r" to update web.config.
Running "Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r" will do the exact same thing as this PR, changing the two lines in web.config. After this I was able to succesfully run tha sample on Outlook on the Web in Edge and Chrome as well as in the …

Update DotNetCompilerPlatform in web.config

---

Samples/auth/Outlook-Add-in-SSO/AttachmentDemo/app.config
Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/AttachmentDemoWeb.csproj
Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Web.config
Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/packages.config

| Related issues? | fixes #1998 |
This should fix the Roslyn csc.exe error described in issue #199. Updated the Microsoft.CodeDom.Providers.DotNetCompilerPlatform Nuget package to v3.6.0.

Fix Roslyn csc.exe error

---

Samples/outlook-encrypt-attachments/src/taskpane/taskpane_appt_compose.html
Samples/outlook-encrypt-attachments/src/taskpane/taskpane_msg_compose.html

| Related issues? | nope |
Minor Typo, text does not match the naming of the attachments (not a prefixed underscore but a trailing underscore.
No Guidance, merely a fix of dialog/Taskpane text

Minor Change - Fixed a couple of typos

---

Samples/word-add-in-get-set-edit-openxml/README.md
Samples/word-add-in-load-and-write-open-xml/README.md

OOXML option not limited to Office 2013 but keep note that RichApi is preferred where needed functionality is available. Related to feedback received on PR https://github.com/OfficeDev/office-js-docs-pr/pull/3237.
OOXML option not limited to Office 2013 but keep note that RichApi is preferred where needed functionality is available.

[Word] Remove unnecessary 2013 limitation in OOXML samples

---

Samples/outlook-set-signature/README.md
Samples/outlook-set-signature/manifest.xml
Samples/outlook-set-signature/src/runtime/Js/autorunshared.js
Samples/outlook-set-signature/src/runtime/Js/autorunweb.js

| Bug fix?             | yes |
| New sample?    | no |
| Related issues? | fixes #293 |
Updated the outlook-set-signature sample to–
- correct the minimum requirement set specified in the manifest to 1.10; and
- add support for Outlook on Mac new UI (preview).
Updated the outlook-set-signature sample to–
- correct the minimum requirement set specified in the manifest to 1.10; and
- add support for Outlook on Mac new UI (preview).

[Outlook] (signature sample) Update requirement set and supported platform

---

Samples/auth/Office-Add-in-ASPNET-SSO/README.md
Samples/auth/Office-Add-in-NodeJS-SSO/README.md
Samples/auth/Outlook-Add-in-SSO/README.md

| Bug fix?        | no                            |
| Related issues? | NA  |
Add security note that the SSO samples are using a pattern of returning the OBO obtained Graph token from middle-tier to client. This will be fixed soon, but for now need to warn developers about this pattern. The risks around this pattern are documented at https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#middle-tier-access-token-request

Add security note to SSO samples

---

Samples/VSTO-shared-code-migration/completed/Cell-Analyzer/Cell-Analyzer.csproj
Samples/VSTO-shared-code-migration/start/Cell-Analyzer/Cell-Analyzer.csproj

| Related issues? | fixes #3485 in office-js-docs-pr |
This removes the manifest certificate references in the CS project files for Visual Studio. They cause an error since the certificates are not provided in the repo. They are not needed.

[VSTO shared migration] remove certificates from CS projects

---

Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/authRedirect.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/fallbackAuthTaskpane.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/ssoAuthES6.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/routes/getFilesRoute.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/server-helpers/obo-auth-helper.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/views/layout.pug
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/authRedirect.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/fallbackAuthTaskpane.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/ssoAuthES6.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/routes/getFilesRoute.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/server-helpers/obo-auth-helper.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/views/layout.pug

This updates the code for fallback auth to use the MSAL cache to acquire the access token. This avoids popping up a dialog to sign in the user on every single REST API call.

[SSO Node JS](Add caching support for fallback auth)

---

Samples/outlook-check-item-categories/README.md
Samples/outlook-check-item-categories/manifest-localhost.xml
Samples/outlook-check-item-categories/manifest.xml
Samples/outlook-check-item-categories/src/commands/commands.html

| Related issues? | N/A|
Removes preview tags and updates the supported build number in the Outlook Smart Alerts sample in preparation for the Mailbox requirement set 1.12 release.
See above.

[Outlook] (Smart Alerts) Remove preview references for Mailbox 1.12 release

---

Samples/excel-data-types-explorer/README.md
Samples/excel-data-types-explorer/package-lock.json
Samples/excel-data-types-explorer/package.json
Samples/excel-data-types-explorer/src/taskpane/taskpane.html
Samples/excel-data-types-explorer/src/taskpane/taskpane.ts

| Related issues? |  #393 |
ExcelApi 1.16 has been released to GA. This PR updates the Data types explorer sample, removing the references to the office-js-preview type definitions and replacing them with office-js type definitions. 
This PR also incorporates the dependabot update to jQuery from PR #393, and switches the icon list in taskpane.ts from a static list to an enum-generated list.

[Data types explorer] Promote sample from preview to GA after release of ExcelApi 1.16

---

Samples/outlook-verify-sensitivity-label/README.md
Samples/outlook-verify-sensitivity-label/manifest-localhost.xml
Samples/outlook-verify-sensitivity-label/manifest.xml
Samples/outlook-verify-sensitivity-label/src/commands/commands.html
Samples/outlook-verify-sensitivity-label/src/taskpane/taskpane.html

| Bug fix?        | no                        |
Updates the sensitivity label sample to remove preview notes/tags in preparation for its release with Mailbox 1.13.
See above.

[Outlook] (sensitivity label) Mailbox 1.13 release

---

Samples/outlook-check-item-categories/README.md

| Bug fix?        | no                          |
| Related issues? | none|
Clarifies that categories applied to a message in compose mode are only viewable from the message once the message is sent and is accessed from the Sent Items folder.
N/A

[Outlook] (Smart Alerts sample) Clarify when categories are viewable from a message in compose mode

---

Samples/outlook-set-signature/manifest.json

Updates the URI for the JSON manifest schema.
Removes a JSON property that is not supported in Outlook.

correct JSON schema URI and remove property unsupported in Outlook

---

Samples/outlook-spam-reporting/src/spamreporting.js

| Bug fix?        | yes |
Moves the `Office.actions.associate` code to the `Office.onReady` call.

[Outlook] (spam reporting) Add Office.onReady function

---

Samples/auth/Outlook-Add-in-SSO-NAA/src/taskpane/authConfig.ts
Samples/auth/Outlook-Add-in-SSO-NAA/src/taskpane/taskpane.ts

Consome getAuthContext API in Outlook to help initialize MSAL.js (get loginHint, and filter to correct account in cache). Also implement loggerOptions behind a flag that can be used to help diagnose MSAL.js errors. The following line can be changed for additional logging: `this.pca = await PublicClientNext.createPublicClientApplication(getMsalConfig(true))`

Consume getAuthContext for Outlook NAA sample and add logging

---

Samples/auth/Outlook-Add-in-SSO-NAA/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA/package.json

@azure/msal-browser adds better logging around of Nested App Auth is available or not in the client, bump the package version which will be useful for diagnostic and bug reports.

Update to @azure/msal-browser 3.14.0 for better logging

---

Samples/office-contextual-tabs/README.md

@akrantz reported that contextual tabs are only supported in Excel. This matches the existing [requirement set documentation](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/ribbon-api-requirement-sets).

Contextual tabs are only supported on Excel

---

README.md
Samples/auth/Outlook-Add-in-SSO-events/README.md
Samples/auth/Outlook-Add-in-SSO-events/manifest.xml
Samples/auth/Outlook-Add-in-SSO/README.md
Samples/hello-world/outlook-hello-world/README.md
Samples/outlook-check-item-categories/README.md
Samples/outlook-check-item-categories/manifest-localhost.xml
Samples/outlook-check-item-categories/manifest.xml
Samples/outlook-encrypt-attachments/README.md
Samples/outlook-encrypt-attachments/manifest-localhost.xml
Samples/outlook-encrypt-attachments/manifest.xml
Samples/outlook-set-signature/README.md
Samples/outlook-spam-reporting/README.md
Samples/outlook-spam-reporting/assets/sample.json
Samples/outlook-spam-reporting/manifest-localhost.xml
Samples/outlook-spam-reporting/manifest.xml
Samples/outlook-tag-external/README.md
Samples/outlook-tag-external/manifest-localhost.xml
Samples/outlook-tag-external/manifest.xml
Samples/outlook-verify-sensitivity-label/README.md
Samples/outlook-verify-sensitivity-label/manifest-localhost.xml
Samples/outlook-verify-sensitivity-label/manifest.xml
Samples/tutorials/outlook-tutorial/README.md

| New feature?    | no                          |
| New sample?     | no                          |
| Related issues? |  None |
- Removes the preview string from new Outlook on Windows references.
- Updates support for new Outlook on Windows where applicable.
Related PRs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70168
- https://github.com/OfficeDev/office-js-docs-pr/pull/4693
- https://github.com/OfficeDev/office-js-docs-reference/pull/2009
- https://github.com/OfficeDev/office-js-snippets/pull/927

[Outlook] (new Outlook on Windows) Remove preview string

---

Samples/excel-insert-file/README.md
Samples/excel-insert-file/index.html

| Bug fix?        | no                      |
| New feature?    | no                 |
| New sample?     | no                          |
| Related issues? | |
The excel-insert-file sample was using the beta CDN instead of the release CDN for office.js. This PR fixes that, as well as updates the readme to reflect the current UI location of the Add-ins dialog.

Use release version of office.js instead of preview

---

Samples/auth/Outlook-Event-SSO-NAA/src/well-known/microsoft-officeaddins-allowed.json

The path in .well-known/microsoft-officeaddins-allowed.json is incorrect and causes the NAA flow to fail. It needs to match the path loaded from the manifest.

Fix wrong script path in NAA event sample

---

Samples/auth/Office-Add-in-SSO-NAA/package-lock.json
Samples/auth/Office-Add-in-SSO-NAA/package.json
Samples/auth/Outlook-Add-in-SSO-NAA-IE/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA-IE/package.json
Samples/auth/Outlook-Add-in-SSO-NAA/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA/package.json
Samples/auth/Outlook-Event-SSO-NAA/package-lock.json
Samples/auth/Outlook-Event-SSO-NAA/package.json

Bump @azure/msal-browser to 3.24.0 for the NAA samples. Version 3.21.0 which was used for a sample has a bug that caused compatibility issues with Office, need to make sure developers aren't using this version.

Bump @azure/msal-browser to 3.24.0 for NAA samples

---

Samples/auth/Outlook-Event-SSO-NAA/package-lock.json
Samples/auth/Outlook-Event-SSO-NAA/package.json
Samples/auth/Outlook-Event-SSO-NAA/webpack.config.js

Older versions of Outlook Win32 event-based runtime does not support ECMAScript version that @azure/msal-browser dependency uses, so it is causing issues loading the launchevent.js bundle. Configure webpack to target ES6 when producing the bundle.

[Outlook] Fix NAA event sample not loading on older runtime versions

---

Samples/outlook-spam-reporting/README.md

| Bug fix?        | no                           |
Documents support for the spam-reporting sample in Outlook on Mac.

[Outlook] (spam reporting) Document support in Outlook on Mac

---

npm-audit-fix.sh

Adds script that runs `npm audit fix` on all package-lock files in repo. Eventually want to have GitHub Action workflow run this periodically.

Add script to run npm audit fix command throughout repo
