OfficeDev/Office-Add-in-samples

Samples/Outlook.RelatedData/src/index.html

The path to highcharts-ng js file is incorrect
(resubmission of PR #5)

Change the wrong path to highcharts-ng

---

Excel-custom-functions/Dialog/dialog.html

Issue 1: in dialog.html, dialog.close does nothing

Fix various issues

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
readme-template.md

| Related issues? | na |
Updating info for contribution guidelines. Also updated readme template for new sample submissions.

Update contributor info and guidelines

---

Samples/dynamic-dpi/VSTO Excel Addin/ExcelAddIn1/app.config
Samples/dynamic-dpi/VSTO SharedAddin/SharedModule/App.config

Adding app.config files that were missing previously.

Adding app.config files

---

README.md

- Added link to the batching sample.
- Added clarification text around PnP program.
No additional guidance.

Added batching pattern link and clarified some text

---

README.md

Added batching pattern link and clarified some text (#44)

---

Excel-custom-functions/Storage/README.md

| Bug fix?        | no                      |
| New feature?    | Adjusts docs for Shared Runtime                              |
| Related issues? | Adjusts docs for Shared Runtime |
Adjustments to Readme text to reflect that this sample is for UI-less custom functions only.

Change to only UI-less CFs

---

Samples/excel-shared-runtime-scenario/manifest.xml
Samples/excel-shared-runtime-scenario/package-lock.json
Samples/excel-shared-runtime-scenario/package.json
Samples/excel-shared-runtime-scenario/src/index.html

| Related issues? | --- |
Update from preview to GA version of libraries to keep sample current.

[shared runtime] update to GA type libraries

---

Excel-custom-functions/AzureFunction/README.md

Azure function app
https://docs.microsoft.com/en-us/samples/officedev/pnp-officeaddins/integrate-an-azure-function-with-your-excel-custom-function/

Typo "Azure function app"→"Azure Function App"

---

Excel-custom-functions/AzureFunction/CustomFunctionProject/src/functions/functions.js
Excel-custom-functions/AzureFunction/README.md

Making sure all instances of Azure Functions are capitalized.

Fix Azure Function capitalization

---

Samples/excel-shared-runtime-scenario/package-lock.json
Samples/excel-shared-runtime-scenario/utilities/office-apis-helpers.ts

| Related issues? | partial fix [office-js #1542](https://github.com/OfficeDev/office-js/issues/1542) |
- Fix bug causing "RichApi.Error: The requested resource doesn't exist" to log to the debug console when choosing the "Load on doc open" button. 
- Ran prettier and npm audit fix

fix #1542 related bugs

---

Samples/excel-shared-runtime-scenario/package-lock.json
Samples/excel-shared-runtime-scenario/package.json

Manifest Validation failed, fixed that by updating the validator engine in office-addin-manifest
No additional guidance, to repro the issue run
npm run validate 
before and after the change

Fixed failed Manifest Validation

---

Samples/excel-keyboard-shortcuts/README.md
Samples/excel-keyboard-shortcuts/package-lock.json
Samples/excel-keyboard-shortcuts/src/shortcuts.json
Samples/excel-keyboard-shortcuts/src/taskpane/taskpane.css
Samples/excel-keyboard-shortcuts/src/taskpane/taskpane.html
Samples/excel-keyboard-shortcuts/src/taskpane/taskpane.js

| New sample?     | modified sample                               |
Changing the shortcut combinations used in the sample to avoid conflicts with existing Excel shortcuts.

Change shortcuts to avoid conflicts with Excel

---

Samples/excel-insert-file/index.js
Samples/excel-insert-file/manifest.xml

Just moves github io url references to this repo on OfficeDev.

transfer page URLs to source repo

---

README.md
Samples/outlook-tag-external/README.md
Samples/outlook-tag-external/manifest.xml

| Bug fix?        | no - yes? No                              |
| New feature?    | no - yes? No                              |
| New sample?     | no - yes?  No                             |
| Related issues? | None |
Updates asset links from fork to final for for the outlook-tag-external sample.

[Outlook] (external tags) Update to final links

---

.github/PULL_REQUEST_TEMPLATE.md
Excel-custom-functions/AsyncStorage/README.md
Samples/excel-insert-file/README.md
Samples/excel-keyboard-shortcuts/README.md
Samples/excel-keyboard-shortcuts/manifest-localhost.xml
Samples/excel-keyboard-shortcuts/manifest.xml
Samples/office-contextual-tabs/README.md
Samples/office-contextual-tabs/manifest-localhost.xml
Samples/office-contextual-tabs/manifest.xml

| Bug fix?        | no - yes?  yes                             |
| New feature?    | no - yes?   no                            |
| New sample?     | no - yes?  no                             |
Update template from "master" to "main" and clean up some links that still said "master"

Update links from master to main

---

Samples/outlook-set-signature/README.md
Samples/outlook-set-signature/src/runtime/HTML/autorunweb.html
Samples/outlook-set-signature/src/taskpane/HTML/assignsignature.html
Samples/outlook-set-signature/src/taskpane/HTML/editsignature.html

Setsignature API is GA, so this is just removing preview text from readme.

[outlook-set-signature] Update to reflect that feature is GA

---

Samples/excel-insert-file/README.md

| Bug fix?        | no - yes?                               |
| New feature?    | no - yes?                               |
| New sample?     | no - yes?                               |
> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to `dev` branch. Released documents are in `main` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

Updating readme as feature is now GA

---

Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNET-SSO-WebAPI/Scripts/HomeES6.js
Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNET-SSO-WebAPI/Views/Shared/_Layout.cshtml
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/ssoAuthES6.js
Samples/auth/Office-Add-in-NodeJS-SSO/SSOAutoSetup/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/SSOAutoSetup/package.json
Samples/auth/Office-Add-in-NodeJS-SSO/SSOAutoSetup/src/public/javascripts/ssoAuthES6.js

Changing sample to use Office.auth interface which is recommended over OfficeRuntime.auth.

Update SSO sample to use Office.auth interface

---

Samples/excel-open-in-teams/README.md
Samples/excel-open-in-teams/excel-open-in-teams/Controllers/ProductsController.cs
Samples/excel-open-in-teams/excel-open-in-teams/Helpers/GraphAPIHelper.cs
Samples/excel-open-in-teams/excel-open-in-teams/Views/Products/ChannelsListForTeam.cshtml
Samples/excel-open-in-teams/excel-open-in-teams/Views/Products/TeamsList.cshtml
Samples/excel-open-in-teams/excel-open-in-teams/appsettings.json

| Bug fix?        | no -                               |
Added code to prevent CSRF in the forms, and also HTML encoding in the controllers to prevent script injection attacks.

[Open in teams] add security checks

---

README.md
Samples/hello-world/excel-hello-world/manifest.xml
Samples/hello-world/outlook-hello-world/manifest.xml
Samples/hello-world/powerpoint-hello-world/manifest.xml
Samples/hello-world/word-hello-world/manifest.xml

Adds the hello world samples to the top readme listing, and also adjusts manifest URLs to use correct GitHub IO page locations in the main branch.

[Hello world](adjust manifest URLs)

---

Samples/office-add-in-commands/README.md
Samples/office-add-in-commands/excel/README.md
Samples/office-add-in-commands/powerpoint/README.md

Hi Dave, I accidentally commited the Word README edits into Main. Those changes are the same as the ones in this PR.

Lindalu readme edits

---

Excel-custom-functions/Batching/README.md
Excel-custom-functions/Storage/README.md
Excel-custom-functions/web-worker/readme.md

| Related issues? | mentioned in #245 |
This PR fixes broken links in the custom functions samples and adds a platform availability note (an issue mentioned in #245).

[Excel] (Custom functions) Fix broken link, add platform availability

---

README.md

| New sample?     | yes                               |
Update readme to reflect migrated samples for Word OOXML (and other minor updates to links and titles for better clarity)

Davech update readme

---

Samples/outlook-encrypt-attachments/README.md

Add internal metadata so sample will be indexed by code sample service. Also, minor cleanup.
Added internal metadata so sample will be indexed by code sample service.

[Outlook] (encrypt attachments) Add internal metadata

---

Samples/word-add-in-get-set-edit-openxml/README.md
Samples/word-add-in-load-and-write-open-xml/README.md

| Related issues? | partially #223 |
Updated the readmes of the Word OOXML samples to point out that APIs in WordApi requirement sets are preferred over OOXML coercion in add-ins targeting Word 2016 or later where the functionality you're looking for is available. Also some minor cleanup.
Readmes of the Word OOXML samples updated to point out that APIs in WordApi requirement sets are preferred over OOXML coercion in add-ins targeting Word 2016 or later where the functionality you're looking for is …

[Word] (ooxml) Update readmes

---

README.md

Updated repo readme to remove preview tag from Outlook external recipients sample in list.
Updated repo readme to remove preview tag from Outlook external recipients sample in list.

[Outlook] (external recipients) Remove preview tag from repo readme

---

Samples/auth/Office-Add-in-Microsoft-Graph-React/README.md
Samples/auth/Office-Add-in-Microsoft-Graph-React/config/webpack.common.js
Samples/auth/Office-Add-in-Microsoft-Graph-React/config/webpack.dev.js
Samples/auth/Office-Add-in-Microsoft-Graph-React/package-lock.json
Samples/auth/Office-Add-in-Microsoft-Graph-React/package.json

Fixes security vulnerabilities in package dependencies by updating package.json and related files.

[Security update](fix package dependencies) Excel React Auth sample

---

Samples/office-contextual-tabs/sample.json

Adds a sample.json file with metadata to list this sample in the [M365 solution gallery](https://adoption.microsoft.com/sample-solution-gallery/).

[Office contextual tabs] add metadata for M365 solution gallery

---

Samples/auth/Office-Add-in-ASPNET-SSO/assets/sample.json
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/assets/sample.json
Samples/auth/Office-Add-in-Microsoft-Graph-React/assets/sample.json
Samples/auth/Office-Add-in-NodeJS-SSO/assets/sample.json
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/assets/sample.json
Samples/auth/Outlook-Add-in-SSO/assets/sample.json
Samples/office-contextual-tabs/sample.json

| New sample?     | no                           |
Adds a sample.json file to the auth samples to get them listed in the [Microsoft 365 sample gallery](https://adoption.microsoft.com/sample-solution-gallery).

[Samples] Add metadata to add samples to M365 gallery

---

CONTRIBUTING.md

Fixes the README template link and updates the repo name from PnP-OfficeAddins to Office-Add-ins-sample in the CONTRIBUTING.md file.

[CONTRIBUTING] Fix README template link and update repo name

---

README.md
Samples/outlook-check-item-categories/manifest.xml

| New sample?     | no                        |
- Update the manifest references in the recently merged 'Use Outlook Smart Alerts' sample.
-  Add the sample to the repo's README.md file.
N/A

[Outlook] (manifest) Update manifest references and add sample to README

---

Office Add-in samples community panel.ics
README.md

Adds info and calendar invite for June 15th sample panel Teams call for samples discussion.

Add June 15th panel call info.

---

Samples/auth/Outlook-Add-in-SSO/README.md

| Related issues? | fixes #306  |
Remove step to use implicit flow.
Add global client app auth to simplify this step.

Remove implicit grant and update authorized client

---

README.md

Add Blazor samples to README file.
None.

[README] Add Blazor samples

---

Samples/hello-world/outlook-hello-world/README.md

| New sample?     | no -                          |
| Related issues? | Fixes #339 |
This fixes a link in the Outlook Hello World sample.

Fix link anchor in Outlook Hello World readme

---

Office Add-in samples community panel.ics
README.md

Adds invite and info about the July sample community call forum.

Add July sample forum call info

---

Excel-custom-functions/Storage/README.md
Excel-custom-functions/Storage/src/taskpane/taskpane.html
Excel-custom-functions/web-worker/functions-worker.js
Excel-custom-functions/web-worker/functions.js
Excel-custom-functions/web-worker/home.html
Excel-custom-functions/web-worker/readme.md
Samples/excel-insert-file/README.md
Samples/excel-insert-file/index.js
Samples/excel-keyboard-shortcuts/src/taskpane.js
Samples/excel-shared-runtime-global-state/src/commands/commands.js
Samples/outlook-tag-external/src/commands/commands.js
Samples/word-add-in-get-set-edit-openxml/C#/WD_OpenXML_jsWeb/App/App.js
Samples/word-add-in-get-set-edit-openxml/C#/WD_OpenXML_jsWeb/App/WD_OpenXML_js/WD_OpenXML_js.js
Samples/word-add-in-get-set-edit-openxml/README.md
Samples/word-add-in-load-and-write-open-xml/C#/LoadingAndWritingOOXMLWeb/App/App.js
Samples/word-add-in-load-and-write-open-xml/C#/LoadingAndWritingOOXMLWeb/App/LoadingAndWritingOOXML/LoadingAndWritingOOXML.js
Samples/word-add-in-load-and-write-open-xml/description/offline.js

| Bug fix?        | no                                   |
| New sample?     | no                             |
| Related issues? | N/A                            |
Replaces 'var' with let/const in JS code, where applicable.
Replaces 'var' with let/const in JS code.

[All hosts] (JS) Update var to let/const in JS code

---

README.md

Since the community panel meeting happened, no need to list it in the readme anymore.

Remove panel invite from readme

---

Samples/auth/Office-Add-in-ASPNET-SSO/Before/Office-Add-in-ASPNET-SSO-WebAPI/Scripts/HomeES6.js
Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNET-SSO-WebAPI/Scripts/HomeES6.js
Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNET-SSO/Office-Add-in-ASPNET-SSOManifest/Office-Add-in-ASPNET-SSO.xml
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/Office-Add-in-Microsoft-Graph-ASPNETWeb/Scripts/Add-in-Home-Index.js
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/Office-Add-in-Microsoft-Graph-ASPNETWeb/Scripts/Document.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/fallbackAuthTaskpane.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/fallbackAuthTaskpane.js
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/Outlook-Add-in-Microsoft-Graph-ASPNETWeb/Scripts/Add-in-Home-Index.js
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/Outlook-Add-in-Microsoft-Graph-ASPNETWeb/Scripts/Document.js
Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Scripts/MessageRead.js

| Related issues? | fixes [#X, partially #Y, mentioned in #Z](https://github.com/OfficeDev/office-js-docs-pr/issues/1710) |
This is to update the type `Microsoft.Office.WebExtension.EventType.DialogMessageReceived`
to `Office.EventType.DialogMessageReceived`
Based on feedback from issue: https://github.com/OfficeDev/office-js-docs-pr/issues/1710

Update DialogMessageReceived to latest type

---

Excel-custom-functions/Batching/README.md

| Related issues? | fixes #372  |
Updating README.md to clarify the benefit of the custom functions batching sample.

[Excel] (Custom Functions) Clarify benefit of batching sample

---

README.md

Adds the custom settings sample to the readme list.

add custom settings sample to readme

---

README.md
Samples/blazor-add-in/excel-blazor-add-in/assets/sample.json
Samples/blazor-add-in/outlook-blazor-add-in/assets/sample.json
Samples/blazor-add-in/word-blazor-add-in/assets/sample.json

Add sample.json file to list sample in the sample gallery.

Add info for sample gallery

---

README.md

Adding a missing link to the new Data types explorer sample.

[Excel] (Data types) Add data types explorer link to main README.md

---

Samples/hello-world/excel-hello-world/README.md
Samples/hello-world/excel-hello-world/taskpane.html

Adds image URL to track diagnostic data on sample runs.

Add diagnostic image

---

Samples/hello-world/excel-hello-world/README.md
Samples/hello-world/powerpoint-hello-world/README.md
Samples/hello-world/word-hello-world/README.md
Samples/office-add-in-commands/excel/README.md
Samples/office-add-in-commands/powerpoint/README.md
Samples/office-add-in-commands/word/README.md
Samples/office-add-in-save-custom-settings/README.md

| Related issues? | [Internal work item](https://office.visualstudio.com/OC/_workitems/edit/6303398) |
PR [[Testing] (Sideload) Divide iPad and Mac desktop sideloading instructions by alison-mk · Pull Request #3515 · OfficeDev/office-js-docs-pr (github.com)](https://github.com/OfficeDev/office-js-docs-pr/pull/3515) divided the **Sideload Office Add-ins on iPad and Mac for testing** article into two articles. This update replaces obsolete links to that article.

[All hosts] Replace references to deleted article

---

Samples/outlook-check-item-categories/README.md
Samples/outlook-check-item-categories/src/commands/commands.js

| Bug fix?        |  yes |
| Related issues? | addresses #416 |
- Adds support for Outlook on Mac to address #416.
- Adds note about Outlook on the web support.
See above.

[Outlook] (Smart Alerts) Add support for Outlook on Mac

---

Samples/blazor-add-in/excel-blazor-add-in/excel-blazor-add-in/Properties/launchSettings.json
Samples/blazor-add-in/excel-blazor-add-in/excel-blazor-sideloader/excel-blazor-sideloader.csproj.user

Adressing this question:
https://github.com/OfficeDev/Office-Add-in-samples/issues/444
Depends on a PR on CBA, I will add the link for the PR here soon.
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CBA/pullrequest/442150
https://user-images.githubusercontent.com/4503299/208124863-8f5a4a70-e8cd-4ad8-b2c9-2c5ed2e71ba0.mp4

Adding changes to make possible to debug blazor add-in

---

Samples/blazor-add-in/outlook-blazor-add-in/outlook-blazor-add-in/Pages/Index.razor.js

The subject was only being grabbed if the message had an attachment length > 0.   Moved it outside of that if statement so this add-in displays data for emails that don't have attachments.
> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
>

Moving the subject grab

---

Samples/auth/Office-Add-in-NodeJS-SSO/Begin/.ENV
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/bin/www
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/manifest/manifest_local.xml
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/document.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/authConfig.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/authRedirect.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/fallbackAuthTaskpane.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/message-helper.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/ssoAuthES6.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/routes/getFilesRoute.js
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/views/index.pug
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/.ENV
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/bin/www
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/manifest/manifest_local.xml
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/document.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/authConfig.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/authRedirect.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/fallbackAuthTaskpane.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/message-helper.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/ssoAuthES6.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/routes/getFilesRoute.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/views/index.pug
Samples/auth/Office-Add-in-NodeJS-SSO/README.md

| Related issues? | na |
- Puts the sample back on default port 3000.
- Refactors code to simplify handling of SSO, fallback auth, and potential auth errors.

Simplify SSO code

---

Samples/excel-create-worksheet-from-web-site/WebApplication/App/authConfig.js

Restore the placeholders for client id and tenant.

Restore placeholders in Create spreadsheet from web site

---

README.md

| Bug fix?        | no                       |
| New sample?     | no -                          |
| Related issues? | none|
This feature was released and should not be tagged preview.

Remove preview tag from Data Types Explorer

---

Excel-custom-functions/AzureFunction/assets/sample.json
Excel-custom-functions/Batching/assets/sample.json
Excel-custom-functions/web-worker/assets/sample.json
Samples/VSTO-shared-code-migration/README.md
Samples/VSTO-shared-code-migration/assets/sample.json
Samples/blazor-add-in/excel-blazor-add-in/README.md
Samples/blazor-add-in/outlook-blazor-add-in/README.md
Samples/blazor-add-in/word-blazor-add-in/README.md
Samples/excel-create-worksheet-from-web-site/README.md
Samples/excel-create-worksheet-from-web-site/assets/sample.json
Samples/excel-data-types-explorer/assets/sample.json
Samples/excel-shared-runtime-global-state/assets/sample.json
Samples/excel-shared-runtime-scenario/assets/sample.json
Samples/hello-world/assets/sample.json
Samples/hello-world/excel-hello-world/assets/sample.json
Samples/hello-world/outlook-hello-world/assets/sample.json
Samples/hello-world/powerpoint-hello-world/assets/sample.json
Samples/hello-world/word-hello-world/assets/sample.json
Samples/office-add-in-commands/excel/README.md
Samples/office-add-in-commands/excel/assets/sample.json
Samples/office-add-in-commands/powerpoint/README.md
Samples/office-add-in-commands/powerpoint/assets/sample.json
Samples/office-add-in-commands/word/README.md
Samples/office-add-in-commands/word/assets/sample.json
Samples/office-add-in-save-custom-settings/assets/sample.json
Samples/outlook-check-item-categories/assets/sample.json
Samples/tutorials/excel-tutorial/My Office Add-in/assets/sample.json

This adds sample.json files to existing samples to ensure they are listed at https://adoption.microsoft.com/en-us/sample-solution-gallery/

Add metadata to list in m365 adoption gallery

---

Samples/excel-create-worksheet-from-web-site/WebApplication/package-lock.json
Samples/excel-data-types-explorer/package-lock.json
Samples/outlook-set-signature/package-lock.json
Samples/tutorials/excel-tutorial/My Office Add-in/package-lock.json

Updating package dependencies to fix security vulnerabilities.

update package dependencies

---

Samples/excel-insert-file/README.md

| Bug fix?        | no                          |
| New feature?    | no                       |
| New sample?     | no                        |
| Related issues? | None |
The Office Insider program is now referred to as the Microsoft 365 Insider program (https://insider.microsoft365.com/). This PR updates references in our documentation.
See above.

Update Office Insider references

---

README.md

| Related issues? | none|
Removes the preview tag from the sensitivity label sample in the repository's README file.
See above.

[Outlook] (sensitivity label) Remove preview tag

---

README.md

| Bug fix?        | no                     |
| New feature?    | no                          |
| New sample?     | no                        |
| Related issues? | Suggestion from https://github.com/OfficeDev/office-js-docs-pr/pull/3986|
Adds the [event-based SSO sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-events) to the repo's README.
None.

[SSO] (sample) Add event-based SSO sample to README

---

Samples/outlook-set-signature/webpack.config.js

| New sample?     | no                             |
Fix compilation on Linux for outlook-set-signature

Fix compilation on Linux for outlook-set-signature

---

Samples/excel-insert-file/README.md

| Related issues? | fixes #564 |
Fixes #564.

Fix the setup steps for localhost

---

Samples/excel-insert-file/README.md
Samples/outlook-set-signature/manifest-localhost.xml

| Related issues? | fixes #575 |
Fixes incorrect URI locations in the localhost manifest.

Fix localhost manifest in outlook set signature sample

---

Samples/Office.TypeScriptAddin/README.md

From what I can tell, the link is no longer safe, and redirects to a scammy, auto-playing, virus scare type website.
It took my browser full-screen and a robot voice told me I had a virus or something...

[VULN] Update README.md

---

Samples/Office.TypeScriptAddin/README.md
Samples/excel-insert-file/README.md

Removing one last reference to a personal site that now seems to be compromised.

Remove bad link

---

README.md

Updates descriptions about completed tutorials in readme.

(tutorials) Update descriptions in readme

---

Samples/blazor-add-in/README.md
Samples/tutorials/powerpoint-tutorial/README.md

- Updates PowerPoint tutorial readme to note Visual Studio support and remove Node.js/npm.
- Includes Outlook in list of add-in samples in Blazor readme

Minor updates to readmes - blazor, powerpoint tutorial

---

README.md
Samples/outlook-check-item-categories/README.md
Samples/outlook-encrypt-attachments/README.md
Samples/outlook-set-signature/README.md
Samples/outlook-tag-external/README.md

| Related issues? | None |
Updates titles of Outlook samples to make them more scenario-focused.

[Outlook] (scenarios) Update titles to be more scenario-focused

---

Samples/outlook-verify-sensitivity-label/README.md

Updates the supported Outlook on Mac version.

[Outlook] (sensitivity label) Update supported Outlook on Mac version

---

Samples/outlook-check-item-categories/README.md
Samples/outlook-verify-sensitivity-label/README.md

| New feature?    | no  |
- Updates links to the Smart Alerts documentation.
- Fixes bare URLs.

[Outlook] (Smart Alerts) Update links to Smart Alerts documentation

---

Samples/blazor-add-in/excel-blazor-add-in/README.md
Samples/blazor-add-in/outlook-blazor-add-in/README.md
Samples/blazor-add-in/word-blazor-add-in/README.md

Adds steps to the readme on how to configure a new Blazor add-in project to support C# debugging. A few questions have come up around this.

Add Blazor C# debug steps

---

Samples/Excel.JsonToOfficeTable/Excel.JsonToOfficeTableWeb/App/Default.aspx
Samples/Excel.OfflineStorageAddin/src/taskpane/taskpane.html
Samples/Excel.TableBindingFormatting/Excel.TableBindingFormattingWeb/App/Home/Home.html
Samples/excel-create-worksheet-from-web-site/WebApplication/App/index.html
Samples/excel-data-types-explorer/src/taskpane/taskpane.html
Samples/excel-insert-file/index.html
Samples/excel-keyboard-shortcuts/src/taskpane.html
Samples/excel-open-in-teams/excel-open-in-teams/Views/Home/Index.cshtml
Samples/excel-shared-runtime-global-state/src/taskpane/taskpane.html
Samples/excel-shared-runtime-scenario/src/taskpane/taskpane.html
Samples/hello-world/powerpoint-hello-world/taskpane.html
Samples/office-add-in-commands/auto-open-task-pane/home.html
Samples/office-add-in-commands/excel/src/taskpane/taskpane.html
Samples/office-add-in-commands/powerpoint/src/taskpane/taskpane.html
Samples/office-add-in-commands/word/src/taskpane/taskpane.html
Samples/office-add-in-save-custom-settings/src/taskpane.html
Samples/office-contextual-tabs/README.md
Samples/office-contextual-tabs/src/taskpane/taskpane.html
Samples/outlook-check-item-categories/src/taskpane/taskpane.html
Samples/outlook-encrypt-attachments/src/taskpane/taskpane_appt_compose.html
Samples/outlook-encrypt-attachments/src/taskpane/taskpane_msg_compose.html
Samples/outlook-set-signature/src/taskpane/HTML/editsignature.html
Samples/outlook-verify-sensitivity-label/src/taskpane/taskpane.html
Samples/tutorials/excel-tutorial/My Office Add-in/src/taskpane/taskpane.html
Samples/tutorials/outlook-tutorial/Git the gist/src/taskpane/taskpane.html
Samples/tutorials/powerpoint-tutorial-yo/My Office Add-in/src/taskpane/taskpane.html
Samples/tutorials/powerpoint-tutorial/HelloWorld/HelloWorldWeb/Home.html
Samples/tutorials/word-tutorial/My Office Add-in/src/taskpane/taskpane.html
Samples/word-add-in-get-set-edit-openxml/C#/WD_OpenXML_jsWeb/App/WD_OpenXML_js/WD_OpenXML_js.html
Samples/word-add-in-load-and-write-open-xml/C#/LoadingAndWritingOOXMLWeb/App/LoadingAndWritingOOXML/LoadingAndWritingOOXML.html

| Bug fix?        | no - yes?                               |
| New feature?    | no - yes?                               |
| New sample?     | no - yes?                               |
Add diagnostic tags.

Add diagnostic tags

---

Samples/outlook-set-signature/assets/sample.json

| New sample?     | no                             |
Update sample.json metadata of sample "outlook-set-signature"

feat: update sample.json of outlook-set-signature

---

Samples/tutorials/outlook-tutorial/Git the gist/assets/sample.json
Samples/tutorials/powerpoint-tutorial-yo/My Office Add-in/assets/sample.json
Samples/tutorials/powerpoint-tutorial/assets/sample.json
Samples/tutorials/word-tutorial/My Office Add-in/assets/sample.json
Samples/word-citation-management/assets/sample.json

Adds sample.json files for completed tutorials and Word citation management sample.

Add sample.json files for tutorials

---

Samples/outlook-verify-sensitivity-label/README.md

| New sample?     | no                           |
Removes the Microsoft 365 Insider program requirement to run the sample.
See above.

[Outlook] (sensitivity label) Remove Microsoft 365 Insider program requirement

---

Samples/hello-world/outlook-hello-world/README.md

| Bug fix?        | yes                         |
| Related issues? | fixes #666 |
- Replaces duplicate information with a link to the Outlook sideloading article. This removes broken screenshots to fix #666.
- Reorganizes the instructions to run the Outlook hello world sample.
See above.

[Outlook] (hello world) Update instructions to run sample

---

Samples/auth/Office-Add-in-NodeJS-SSO/Begin/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/package.json
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/dialog.html
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/public/javascripts/fallback-msal/authRedirect.js
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/dialog.html
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/public/javascripts/fallback-msal/authRedirect.js

Updates the MSAL browser and node libraries to latest secure versions.

Update MSAL browser and node library versions

---

Samples/auth/Outlook-Add-in-SSO-events/package-lock.json
Samples/auth/Outlook-Add-in-SSO-events/package.json
Samples/auth/Outlook-Add-in-SSO-events/public/taskpane/taskpane.js
Samples/auth/Outlook-Add-in-SSO/AttachmentDemo-ASPNETCore/wwwroot/js/MessageRead.js

| Bug fix?        | no                        |
- Updated the msal-node library to latest version.
- Added commented versions of the forMSGraphAccess parameter (helps avoid the 13012 error on Outlook).

Update msal-node library version

---

Samples/blazor-add-in/excel-blazor-add-in/README.md
Samples/blazor-add-in/excel-blazor-add-in/excel-blazor-add-in/BlazorAddIn.csproj
Samples/blazor-add-in/excel-blazor-add-in/excel-blazor-add-in/wwwroot/index.html
Samples/blazor-add-in/excel-blazor-add-in/excel-blazor-sideloader/excel-blazor-sideloaderManifest/excel-blazor-sideloader.xml
Samples/blazor-add-in/outlook-blazor-add-in/README.md
Samples/blazor-add-in/outlook-blazor-add-in/outlook-blazor-add-in/BlazorAddIn.csproj
Samples/blazor-add-in/outlook-blazor-add-in/outlook-blazor-add-in/wwwroot/index.html
Samples/blazor-add-in/outlook-blazor-add-in/outlook-blazor-sideloader/outlook-blazor-sideloaderManifest/outlook-blazor-sideloader.xml
Samples/blazor-add-in/word-blazor-add-in/README.md
Samples/blazor-add-in/word-blazor-add-in/word-blazor-add-in/BlazorAddIn.csproj
Samples/blazor-add-in/word-blazor-add-in/word-blazor-add-in/wwwroot/index.html
Samples/blazor-add-in/word-blazor-add-in/word-blazor-sideloader/word-blazor-sideloaderManifest/word-blazor-sideloader.xml

| New feature?    |  yes                               |
This Pull Request updates the Blazor Samples to the latest .NET version 8.0.1
The Blazor Samples solutions should still work as is. I tested the add-ins and ran without issues.
This update will prepare the solutions to be able to make use of the new Blazor Hybrid solutions mixing Server-Side Rendering and Client-Side Rendering.

Updated .NET version from 6.0 to 8.0

---

Samples/Excel.JsonToOfficeTable/Excel.JsonToOfficeTableWeb/App/App.js
Samples/Excel.OfflineStorageAddin/src/taskpane/taskpane.js
Samples/Excel.TableBindingFormatting/Excel.TableBindingFormattingWeb/App/Home/Home.js
Samples/Office.TypeScriptAddin/Office.TypeScriptAddinWeb/AddIn/Home/Home.ts
Samples/auth/Office-Add-in-ASPNET-SSO/Begin/Office-Add-in-ASPNETCore-WebAPI/wwwroot/js/HomeES6.js
Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNETCore-WebAPI/wwwroot/js/HomeES6.js
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/Office-Add-in-Microsoft-Graph-ASPNETWeb/Scripts/Document.js
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/Outlook-Add-in-Microsoft-Graph-ASPNETWeb/Scripts/Document.js
Samples/tutorials/powerpoint-tutorial/HelloWorld/HelloWorldWeb/Home.js
Samples/word-add-in-load-and-write-open-xml/C#/LoadingAndWritingOOXMLWeb/App/LoadingAndWritingOOXML/LoadingAndWritingOOXML.js
Samples/word-citation-management/src/taskpane/taskpane.js
Templates/PowerPoint.MVCAddInTemplate/PowerPoint.MVCAddInTemplateWeb/Scripts/Home/Home.js

| Related issues? | internal |
This PR changes deprecated jQuery calls to the correct equivalents.

Update jQuery to use on instead of click

---

Samples/outlook-set-signature/manifest.json

| Bug fix?        | yes                             |
A change to the JSON manifest schema was pushed to Office without warning doc team. This updates the manifest so it is valid again.

property name in json manifest has changed

---

Samples/word-import-template/assets/sample.json
Samples/word-import-template/manifest.xml
Samples/word-import-template/src/taskpane/taskpane.html

Update manifest to use main and add sample.json.

[Word] (import template) Update to use main

---

Samples/auth/Office-Add-in-NodeJS-SSO/Begin/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/package.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package.json
Samples/auth/Outlook-Add-in-SSO-events/package-lock.json
Samples/auth/Outlook-Add-in-SSO-events/package.json

Updates packages to latest versions to be sure there are no security vulnerabilities.

Update packages to latest versions

---

README.md
Samples/outlook-spam-reporting/README.md
Samples/outlook-spam-reporting/assets/sample.json

Updates README files and adds a sample.json file to the Outlook spam-reporting sample.

[Outlook] (spam reporting) Update README files and add sample.json file

---

SECURITY.md
Samples/Excel.JsonToOfficeTable/Excel.JsonToOfficeTableWeb/Scripts/jquery-1.9.1.js
Samples/Excel.TableBindingFormatting/Excel.TableBindingFormattingWeb/Scripts/jquery-1.9.1.js
Samples/Office.ASP.NETCoreReactAddins/excel-js/ClientApp/README.md
Samples/Office.ASP.NETCoreReactAddins/excel-ts/ClientApp/README.md
Samples/Office.TypeScriptAddin/Office.TypeScriptAddinWeb/Scripts/jquery-1.9.1.js
Samples/Outlook.ConsumeGraphAPI/Outlook.AddInSampleWeb/Scripts/jquery-1.9.1.js
Samples/Outlook.MailCRM/DXDemos.Office365/Controllers/AccountController.cs
Samples/Outlook.MailCRM/DXDemos.Office365/Scripts/angular.js
Samples/Outlook.MailCRM/DXDemos.Office365/Scripts/bootstrap.js
Samples/Outlook.MailCRM/DXDemos.Office365/Scripts/jquery-1.10.2.js
Samples/Outlook.MailCRM/DXDemos.Office365/Scripts/jquery.signalR-2.1.2.js
Samples/Outlook.UpsPackageTracker/UPSPackageTrackerWeb/Scripts/jquery-2.1.3.js
Samples/Outlook.YouTubeApp/Outlook.YouTubeAppWeb/Scripts/jquery-1.9.1.js
Samples/excel-open-in-teams/excel-open-in-teams/Controllers/ProductsController.cs
Samples/excel-open-in-teams/excel-open-in-teams/wwwroot/lib/bootstrap/dist/js/bootstrap.js
Samples/excel-open-in-teams/excel-open-in-teams/wwwroot/lib/jquery/dist/jquery.js
Templates/Excel.MVCAddInTemplate/Excel.MVCAddInTemplateWeb/Scripts/jquery-1.10.2.js
Templates/Outlook.MVCAddInTemplate/Outlook.MVCAddInTemplateWeb/Scripts/jquery-1.10.2.js
Templates/PowerPoint.MVCAddInTemplate/PowerPoint.MVCAddInTemplateWeb/Scripts/jquery-1.10.2.js
Templates/Word.MVCAddInTemplate/Word.MVCAddInTemplateWeb/Scripts/jquery-1.10.2.js

| Bug fix?        | no                          |
| New sample?     | no                          |
| Related issues? | None |
This PR removes militaristic language from these docs.

[all] (Language) Adjust language for new security guidelines

---

Samples/auth/Outlook-Add-in-SSO-NAA/README.md

Fixes the screenshots in the README file.

[Outlook] (auth) Fix screenshots

---

Samples/outlook-spam-reporting/README.md

- Adds Outlook on the web and new Outlook on Windows as supported clients.
- Removes preview strings.

[Outlook] (spam reporting) Document other supported platforms and remove preview strings

---

Samples/outlook-set-signature/README.md
Samples/outlook-set-signature/package.json

Update signature sample to reflect GA of unified manifest:
1. Changes the names of scripts in the package.json to make the unified manifest the normal case and make the xml manifest the special case that requires specially named scripts. 
2. Updates the Readme to reflect 1 and to remove verbiage that says the unified manifest is in preview.

Update signature sample to reflect GA of unified manifest

---

Samples/auth/Outlook-Add-in-SSO-NAA/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA/package.json
Samples/auth/Outlook-Add-in-SSO-NAA/src/taskpane/authConfig.ts

Upgrade msal-browser to 3.15.0 for Nested App Auth Outlook sample.

Upgrade msal-browser to 3.15.0

---

Samples/word-import-template/README.md

|        Q                |         A           |
| ----------------- | -------------- |
| Bug fix?             | sort of           |
| New feature?     | no                |
| New sample?     | no                |
Updated procedure to MSFT style (i.e.. we don't say "on the ribbon".) Also, trying to create a new build to see if this sample will get picked up in the samples.json file. Currently, it's missing for some reason. Webhook was recently updated, so that could have something to do with it. Ultimate goal is this sample will appear in gallery and in the automated swimlane in Word Dev Center.

Update README.md procedure

---

Samples/Office.ASP.NETCoreReactAddins/excel-js/ClientApp/package-lock.json
Samples/Office.ASP.NETCoreReactAddins/excel-js/ClientApp/package.json
Samples/Office.ASP.NETCoreReactAddins/excel-ts/ClientApp/package-lock.json
Samples/Office.ASP.NETCoreReactAddins/excel-ts/ClientApp/package.json

This PR updates a couple packages to account for potential security issues.

Update Office.ASP.NETCoreReactAddins sample package.json files

---

Samples/word-import-template/README.md
Samples/word-import-template/assets/sample.json

Update metadata to match actual sample name.

[Word] (import template) Update metadata

---

Samples/outlook-spam-reporting/README.md
Samples/outlook-spam-reporting/manifest.xml
Samples/outlook-spam-reporting/src/spamreporting_classic.js

| Related issues? | Fixes #798 |
Creates a separate event-handling JavaScript file for classic Outlook on Windows.

[Outlook] (spam reporting) Separate event-handling JavaScript files

---

Excel-custom-functions/AzureFunction/README.md
Samples/Excel.TableBindingFormatting/README.md
Samples/Office.ASP.NETCoreReactAddins/README.md
Samples/VSTO-shared-code-migration/README.md
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/README.md
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/README.md
Samples/auth/Outlook-Add-in-SSO/README.md
Samples/dynamic-dpi/readme.md

Update according to [current guidance](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/right-click) so instruction isn't mouse-centric.

Update references to right-click

---

Samples/excel-keyboard-shortcuts/README.md

| New sample?     | no|
| Related issues? | |
A sentence that explains in more detail why a developer would want to add keyboard shortcuts to their add-in.

[excel] (Keyboard Shortcuts) Adding some readme text to further explain the scenarios

---

Samples/outlook-set-signature/manifest.json

| New sample?     | no                             |
| Related issues? | |
Update the outlook-set-signature sample to use the release version of the unified manifest schema.

Update json manifest to GA version

---

Samples/outlook-spam-reporting/manifest-localhost.xml

Updates the referenced JavaScript file in the `manifest-localhost.xml` file to match the `manifest.xml` file.

[Outlook] (spam reporting) Update referenced JS file in localhost manifest

---

Samples/excel-shared-runtime-global-state/README.md

| New sample?     | no                   |
Small change to have the title of the sample better reflect the scenario.

[excel] (Shared Runtime) Switch the title to focus on the scenario instead of the feature

---

Samples/Excel.OfflineStorageAddin/package-lock.json
Samples/excel-create-worksheet-from-web-site/WebApplication/package-lock.json
Samples/excel-data-types-explorer/package-lock.json
Samples/outlook-set-signature/package-lock.json
Samples/tutorials/excel-tutorial/My Office Add-in/package-lock.json
Samples/tutorials/outlook-tutorial/Git the gist/package-lock.json
Samples/tutorials/powerpoint-tutorial-yo/My Office Add-in/package-lock.json
Samples/tutorials/word-tutorial/My Office Add-in/package-lock.json
Samples/word-citation-management/package-lock.json

| New sample?     | no -                            |
This PR runs `npm audit fix` on several samples to address security vulnerabilities in the dependencies.

Running npm audit fix on several samples

---

Samples/office-keyboard-shortcuts/README.md

| Bug fix?        | no                          |
| New feature?    | no                          |
| New sample?     | no                          |
Fixes the indentation of the note in the README, so that it renders correctly.

[Word] (keyboard shortcuts) Fix format of note

---

Samples/auth/Outlook-Add-in-SSO-NAA/README.md

This PR fixes the README of NAA sample that had a path moved.

Fix path to file in NAA Outlook sample README

---

Samples/Excel.OfflineStorageAddin/src/taskpane/taskpane.html
Samples/Outlook.ConsumeGraphAPI/Outlook.AddInSampleWeb/MessageRead.html
Samples/VSTO-shared-code-migration/completed/CellAnalyzerOfficeAddinWeb/Home.html
Samples/VSTO-shared-code-migration/completed/CellAnalyzerWebAddinWeb/Home.html
Samples/auth/Office-Add-in-ASPNET-SSO/Begin/Office-Add-in-ASPNETCore-WebAPI/Views/Shared/_Layout.cshtml
Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNETCore-WebAPI/Views/Shared/_Layout.cshtml
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/Office-Add-in-Microsoft-Graph-ASPNETWeb/Views/Shared/_Layout.cshtml
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/views/layout.pug
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/views/layout.pug
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/Outlook-Add-in-Microsoft-Graph-ASPNETWeb/Views/Shared/_Layout.cshtml
Samples/tutorials/powerpoint-tutorial/HelloWorld/HelloWorldWeb/Home.html
Templates/Excel.MVCAddInTemplate/Excel.MVCAddInTemplateWeb/Views/Shared/_Layout.cshtml
Templates/Outlook.MVCAddInTemplate/Outlook.MVCAddInTemplateWeb/Views/Shared/_Layout.cshtml
Templates/PowerPoint.MVCAddInTemplate/PowerPoint.MVCAddInTemplateWeb/Views/Shared/_Layout.cshtml
Templates/Word.MVCAddInTemplate/Word.MVCAddInTemplateWeb/Views/Shared/_Layout.cshtml

| Bug fix?        | no                            |
| New feature?    | no                           |
Updates the Fabric Core URL in additional files.

[All hosts] Update additional Fabric URL instances

---

Samples/auth/Outlook-Add-in-SSO-NAA-IE/README.md
Samples/auth/Outlook-Add-in-SSO-NAA-IE/assets/sample.json
Samples/auth/Outlook-Add-in-SSO-NAA/README.md
Samples/auth/Outlook-Add-in-SSO-NAA/assets/sample.json
Samples/auth/Outlook-Add-in-SSO-NAA/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA/package.json
Samples/auth/Outlook-Event-SSO-NAA/README.md
Samples/auth/Outlook-Event-SSO-NAA/assets/sample.json

Removes preview information now that NAA is GA for Outlook.

[Outlook] (NAA) remove preview

---

Samples/Office.ASP.NETCoreReactAddins/excel-js/ClientApp/package-lock.json
Samples/Office.ASP.NETCoreReactAddins/excel-ts/ClientApp/package-lock.json
Samples/auth/Office-Add-in-Microsoft-Graph-React/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA-IE/package-lock.json
Samples/auth/Outlook-Add-in-SSO-events/package-lock.json
Samples/excel-create-worksheet-from-web-site/WebApplication/package-lock.json
Samples/tutorials/excel-tutorial/My Office Add-in/package-lock.json
Samples/tutorials/first-run-experience-tutorial/My Office Add-in/package-lock.json
Samples/tutorials/outlook-tutorial/Git the gist/package-lock.json
Samples/tutorials/powerpoint-tutorial-yo/My Office Add-in/package-lock.json
Samples/tutorials/word-tutorial/My Office Add-in/package-lock.json
Samples/word-citation-management/package-lock.json

| Related issues? | |
This PR runs `npm audit fix` on several samples to address security vulnerabilities and update dependencies.

Run npm audit fix on a few samples

---

Samples/office-keyboard-shortcuts/README.md
Samples/office-keyboard-shortcuts/manifest.xml
Samples/office-keyboard-shortcuts/src/shortcuts.json
Samples/office-keyboard-shortcuts/src/taskpane.html

| Bug fix?        | yes                           |
| New sample?     | no                 |
| Related issues? | fixes #896  |
- Updates the shortcuts used in the sample to avoid conflicts with the Word client.
- Clarifies support in Word on the web. A separate PR will be created to address this in related documentation.

[Word] (keyboard shortcuts) Fix shortcuts and add note about support in Word on the web

---

Samples/excel-add-in-chart-analyze-data/README.md
Samples/excel-add-in-chart-analyze-data/RUN_WITH_EXTENSION.md
Samples/excel-add-in-chart-analyze-data/src/taskpane/taskpane.ts
Samples/excel-add-in-custom-functions-using-web-workers/README.md
Samples/excel-add-in-custom-functions-using-web-workers/RUN_WITH_EXTENSION.md
Samples/excel-add-in-mail-merge/README.md
Samples/excel-add-in-mail-merge/RUN_WITH_EXTENSION.md
Samples/excel-add-in-shape-dashboard/README.md
Samples/excel-add-in-shape-dashboard/RUN_WITH_EXTENSION.md
Samples/excel-add-in-shape-dashboard/src/taskpane/taskpane.html
Samples/excel-get-started-with-dev-kit/README.md
Samples/excel-get-started-with-dev-kit/RUN_WITH_EXTENSION.md
Samples/word-ai-generated-content/README.md
Samples/word-ai-generated-content/RUN_WITH_EXTENSION.md
Samples/word-get-started-with-dev-kit/README.md
Samples/word-get-started-with-dev-kit/RUN_WITH_EXTENSION.md

Fix several dev kit bugs found by @Rick-Kirkham

[Fix] several Dev Kit sample bugs

---

ADD_SAMPLE_INTO_DEV_KIT.md

Update the testing process about how to test Dev Kit samples in dev or other branches.

Update Dev Kit sample testing process

---

Samples/Office.ASP.NETCoreReactAddins/excel-ts/ClientApp/package-lock.json
Samples/excel-create-worksheet-from-web-site/WebApplication/package-lock.json

Updating the package-lock.json files in a couple samples based on `npm audit fix`.

Running npm audit fix on a few samples

---

Samples/excel-add-in-shape-dashboard/src/taskpane/taskpane.html
Samples/word-get-started-with-dev-kit/README.md

| Bug fix?        | no -                           |
Merging the contents of the dev branch to the main branch.

Publish to main

---

Samples/office-keyboard-shortcuts/src/taskpane.html
Samples/outlook-check-item-categories/src/taskpane/taskpane.js

Update how shortcuts are displayed in HTML by using the `kbd` tag.

[all hosts] Use kbd in HTML and js files

---

Samples/outlook-spam-reporting/src/spamreporting.html

Updates the Office.js CDN URL.

[Outlook] (spam reporting) Update CDN URL

---

Samples/office-add-in-commands/excel/README.md
Samples/office-add-in-commands/powerpoint/README.md
Samples/office-add-in-commands/word/README.md

Fix broken image links and other minor cleanup in the add-in commands samples.

(add-in commands) Minor cleanup in readmes

---

Samples/auth/Office-Add-in-ASPNET-SSO/Begin/Office-Add-in-ASPNET-SSO/packages.config
Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNET-SSO/packages.config
Samples/auth/Office-Add-in-Microsoft-Graph-ASPNET/Office-Add-in-Microsoft-Graph-ASPNETWeb/packages.config
Samples/auth/Office-Add-in-Microsoft-Graph-React/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Begin/package-lock.json
Samples/auth/Office-Add-in-NodeJS-SSO/Complete/package-lock.json
Samples/auth/Office-Add-in-SSO-NAA/manifest-configurations/add-in-only/package-lock.json
Samples/auth/Office-Add-in-SSO-NAA/manifest-configurations/unified/package-lock.json
Samples/auth/Office-Add-in-SSO-NAA/package-lock.json
Samples/auth/Outlook-Add-in-Microsoft-Graph-ASPNET/Outlook-Add-in-Microsoft-Graph-ASPNETWeb/packages.config
Samples/auth/Outlook-Add-in-SSO-NAA-IE/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA-Identity/API/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA-Identity/SPA/package-lock.json
Samples/auth/Outlook-Add-in-SSO-NAA/package-lock.json
Samples/auth/Outlook-Add-in-SSO-events/package-lock.json
Samples/auth/Outlook-Event-SSO-NAA/package-lock.json
Samples/excel-add-in-custom-functions-using-web-workers/package-lock.json
Samples/excel-create-worksheet-from-web-site/WebApplication/package-lock.json
Samples/hello-world/outlook-hello-world/package-lock.json
Samples/hello-world/powerpoint-hello-world/manifest-configurations/unified/package-lock.json
Samples/word-add-label-on-open/package-lock.json
Samples/word-citation-management/manifest-configurations/add-in-only/package-lock.json

| Bug fix?        |                      |
| New feature?    |                                |
| New sample?     | |
This PR resolves various dependency version concerns.

Update packages to avoid security issues

---

.github/workflows/autorun-npm-audit-fix.yml

Makes fixes to address workflow failure

[Admin] Debug audit fix workflow

---

.github/workflows/autorun-npm-audit-fix.yml

Finalizes autorun-npm-audit-fix workflow. Scheduled to run mid-month, creates a branch if there are changes.

[Admin] Final version of autorun-npm-audit-fix workflow
